[[plugins]]
repo = "lambdalisue/fern.vim"
hook_add = '''
let g:fern#renderer = 'nerdfont'
nnoremap <C-n> :Fern . -reveal=% -drawer -right -width=35  <CR>


let g:fern#default_hidden=1 "不可視ファイルを表示する

'''

[[plugins]]
repo = 'junegunn/fzf'
build = '''
./install --all
'''
merged = 0
[[plugins]]
repo = "lambdalisue/fern-git-status.vim"

[[plugins]]
repo = "lambdalisue/nerdfont.vim"

[[plugins]]
repo = "lambdalisue/fern-renderer-nerdfont.vim"

# [[plugins]]
# repo = 'LumaKernel/fern-mapping-fzf.vim'
# depends = ['fzf', 'fern.vim']

[[plugins]]
repo = "lambdalisue/glyph-palette.vim"

hook_add = '''
  augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END

'''
# [[plugins]]
# repo = "yuki-yano/fern-preview.vim"
# hook_add = '''
#   function! s:fern_settings() abort
#   nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
#   nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
#   nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
#   nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
# endfunction
# 
# augroup fern-settings
#   autocmd!
#   autocmd FileType fern call s:fern_settings()
# augroup END
# '''

[[plugins]]
repo = "lambdalisue/fern-bookmark.vim"
[[plugins]]
repo = "lambdalisue/fern-hijack.vim"

# [[plugins]]
# repo = 'dracula/vim'
# name = 'dracula-vim'
[[plugins]]
repo = "dracula/vim"


[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
let g:auto_save = 1
'''


[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja'
# [[plugins]]
# repo = "nathanaelkane/vim-indent-guides"
# hook_add = '''
# IndentGuidesEnable
# '''
# set show_end_of_line = true


[[plugins]]
repo = "vim-airline/vim-airline"

# [[plugins]]
# repo = "vim-airline/vim-airline-themes"
# hook_add = '''
# 
# 
# '''

#//[[plugins]]
# // repo ="cespare/vim-toml"
[[plugins]]
repo = "cohama/lexima.vim"

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
#  on_i = 1
merged = 0
hook_add = '''
  let g:coc_global_extensions = [
  \  "coc-clangd",
  \  "coc-css",
  \  "coc-deno",
  \  "coc-docker",
  \  "coc-emmet",
  \  "coc-eslint",
  \  "coc-flutter",
  \  "coc-fzf-preview",
  \  "coc-git",
  \  "coc-json",
  \  "coc-jsref",
  \  "coc-lists",
  \  "coc-markdown-preview-enhanced",
  \  "coc-markdownlint",
  \  "coc-marketplace",
  \  "coc-npm-version",
  \  "coc-prettier",
  \  "coc-prisma",
  \  "coc-react-refactor",
  \  "coc-rls",
  \  "coc-rust-analyzer",
  \  "coc-sh",
  \  "coc-simple-react-snippets",
  \  "coc-snippets",
  \  "coc-svelte",
  \  "coc-tabnine",
  \  "coc-tailwindcss",
  \  "coc-toml",
  \  "coc-tsserver",
  \  "coc-vetur",
  \  "coc-webview",
  \  "coc-yaml"
  \]
  " Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'

 '''
# [[plugins]]

#   repo = "Shougo/ddc.vim"

[[plugins]]
repo = "vim-denops/denops.vim"

[[plugins]]
repo = "alvan/vim-closetag"

#[[plugins]]
#  repo = "github/copilot.vim"
[[plugins]]
repo = "lukas-reineke/indent-blankline.nvim"
#[[plugins]]
#  repo = "mxw/vim-jsx"
#  hook_add = '''
#  let g:jsx_indent_level = 2
#  let g:jsx_indent_props = 2
#  '''


[[plugins]]
repo = "p00f/nvim-ts-rainbow"
hook_add = '''
'''

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
merged = 0

[[plugins]]
repo = "tomtom/tcomment_vim"
#[[plugins]] 
#repo = "mattn/emmet-vim"


[[plugins]]
repo = "t9md/vim-quickhl"
hook_add = '''
nmap <Space>m <Plug>(quickhl-manual-this)
xmap <Space>m <Plug>(quickhl-manual-this)
nmap <Space>M <Plug>(quickhl-manual-reset)
xmap <Space>M <Plug>(quickhl-manual-reset)
'''

#[[plugins]]
#repo = "rbtnn/vim-coloredit"
#hook_add = '''
#nnoremap ce    :<C-u>ColorEdit<cr>  
#'''
#[[plugins]]
#repo = "shmargum/vim-sass-colors"

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "MunifTanjim/nui.nvim"

# [[plugins]]
# repo = 'SirVer/ultisnips'
# hook_add = '''
#   let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/nvim/UltiSnips']
#   let g:UltiSnipsExpandTrigger="<Down>"
# '''
[[plugins]]
repo = "lambdalisue/gina.vim"


[[plugins]]
repo = "RRethy/vim-illuminate"
hook_add = '''
let g:Illuminate_delay ="300"
'''


[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = "windwp/nvim-ts-autotag"
