[[plugins]]
repo = "lambdalisue/fern.vim"
hook_add = '''
let g:fern#renderer = 'nerdfont'
nnoremap <C-n> :Fern . -reveal=% -drawer -right -toggle -width=40  <CR>
let g:fern#default_hidden=1 "不可視ファイルを表示する

'''
[[plugins]]
  repo = "lambdalisue/fern-git-status.vim"

[[plugins]]
  repo = "lambdalisue/nerdfont.vim"

[[plugins]]
  repo = "lambdalisue/fern-renderer-nerdfont.vim"

[[plugins]]
  repo = "yuki-yano/fern-preview.vim"
  hook_add='''
  function! s:fern_settings() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction

augroup fern-settings
  autocmd!
  autocmd FileType fern call s:fern_settings()
augroup END
'''


[[plugins]]
  repo = "lambdalisue/fern-hijack.vim" 
[[plugins]]

  repo = "lambdalisue/glyph-palette.vim"
[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

