[[plugins]]
repo = "lambdalisue/fern.vim"
hook_add = '''
let g:fern#renderer = 'nerdfont'
nnoremap <C-n> :Fern . -reveal=% -drawer -right -width=35  <CR>


let g:fern#default_hidden=1 "不可視ファイルを表示する

'''

[[plugins]]
repo = 'junegunn/fzf'
build = '''
./install --all
'''
merged = 0
[[plugins]]
  repo = "lambdalisue/fern-git-status.vim"

[[plugins]]
  repo = "lambdalisue/nerdfont.vim"

[[plugins]]
  repo = "lambdalisue/fern-renderer-nerdfont.vim"

[[plugins]]
repo = 'LumaKernel/fern-mapping-fzf.vim'
depends = ['fzf', 'fern.vim']

[[plugins]]
  repo ="lambdalisue/glyph-palette.vim"

  hook_add = '''
  augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END

'''
[[plugins]]
  repo = "yuki-yano/fern-preview.vim"
  hook_add='''
  function! s:fern_settings() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction

augroup fern-settings
  autocmd!
  autocmd FileType fern call s:fern_settings()
augroup END
'''

[[plugins]]
  repo = "lambdalisue/fern-bookmark.vim"
[[plugins]]
  repo = "lambdalisue/fern-hijack.vim"

# [[plugins]]
# repo = 'dracula/vim'
# name = 'dracula-vim'
[[plugins]]
repo = "dracula/vim"
hook_add='''

'''


[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
'''

#build_on = '''
#./install -all
#'''

#[[plugins]]
# repo = 'junegunn/fzf.vim'
# colorscheme = "dracula"
# colorscheme_bg = "dark"



# [[plugins]]
# repo ="neoclide/coc.nvim"
# rev = 'release'
# on_i = 1
# merged = '0'
# hook_source = 'call coil398#init#coc#hook_source()'
# ここに入れるのです







[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja'
# [[plugins]]
# repo = "nathanaelkane/vim-indent-guides"
# hook_add = '''
# IndentGuidesEnable
# '''
# set show_end_of_line = true


[[plugins]]
  repo = "vim-airline/vim-airline"

# '''lugins]]
  # repo = "vim-airline/vim-airline-themes"

#//[[plugins]]
# // repo ="cespare/vim-toml"
[[plugins]]
  repo = "cohama/lexima.vim"

[[plugins]]
 repo = 'neoclide/coc.nvim'
 rev = 'release'
#  on_i = 1
 merged = 0
 hook_add = '''
 '''
# [[plugins]]
#   repo = "Shougo/ddc.vim"

 [[plugins]]
   repo = "vim-denops/denops.vim"

# [[plugins]]
#   repo = "Shougo/pum.vim"
#  hook_add = '''
#  inoremap <Tab>   <Cmd>call pum#map#insert_relative(+1)<CR>
# inoremap <S-Tab> <Cmd>call pum#map#insert_relative(-1)<CR>
# inoremap <C-n>   <Cmd>call pum#map#insert_relative(+1)<CR>
# inoremap <C-p>  <Cmd>call pum#map#insert_relative(-1)<CR>
# inoremap <C-y>   <Cmd>call pum#map#confirm()<CR>
# inoremap <C-e>   <Cmd>call pum#map#cancel()<CR>
# inoremap <PageDown> <Cmd>call pum#map#insert_relative_page(+1)<CR>
# inoremap <PageUp>   <Cmd>call pum#map#insert_relative_page(-1)<CR>

#   '''
# [[plugins]]
#   repo = "Shougo/ddc-around"
# [[plugins]]
#   repo = "Shougo/ddc-matcher_head"
# [[plugins]]  
#   repo = "LumaKernel/ddc-file"
# [[plugins]]
#   repo = "Shougo/ddc-sorter_rank"
# [[plugins]]
#   repo = "Shougo/ddc-converter_remove_overlap"

#######################################



# [[plugins]]
#   repo = "prabirshrestha/vim-lsp"
# hook_add = '''
# '''
# [[plugins]]
#   repo =  "mattn/vim-lsp-settings"
# hook_add = '''
#   " Hide signcolumn.
#   let g:lsp_diagnostics_signs_enabled = 0
# '''
# hook_post_source = '''
#   " Highlight LSP warnings strongly (like errors)
#   highlight link LspWarningHighlight Error
#     " Show diagnostics message to status line
#   let g:lsp_diagnostics_echo_cursor = 1

# '''
[[plugins]]
  repo ="alvan/vim-closetag"

#[[plugins]]
#  repo = "github/copilot.vim"
[[plugins]]
  repo = "lukas-reineke/indent-blankline.nvim"
  hook_add = '''




  '''
#[[plugins]]
#  repo = "mxw/vim-jsx"
#  hook_add = '''
#  let g:jsx_indent_level = 2
#  let g:jsx_indent_props = 2
#  '''




[[plugins]]
repo = "p00f/nvim-ts-rainbow"
hook_add =  '''
'''

[[plugins]]
  repo ="nvim-treesitter/nvim-treesitter"
  merged = 0

[[plugins]]
  repo ="tomtom/tcomment_vim"
[[plugins]] 
repo = "mattn/emmet-vim"


[[plugins]]
repo ="t9md/vim-quickhl"
hook_add = '''
nmap <Space>m <Plug>(quickhl-manual-this)
xmap <Space>m <Plug>(quickhl-manual-this)
nmap <Space>M <Plug>(quickhl-manual-reset)
xmap <Space>M <Plug>(quickhl-manual-reset)
'''


[[plugins]]
repo ="rbtnn/vim-coloredit"
hook_add =  '''
nnoremap ce    :<C-u>ColorEdit<cr>  
'''
[[plugins]]
repo = "shmargum/vim-sass-colors"

[[plugins]]
repo ="airblade/vim-gitgutter"

[[plugins]]
repo = "MunifTanjim/nui.nvim"

# [[plugins]]
# repo = 'SirVer/ultisnips'
# hook_add = '''
#   let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/nvim/UltiSnips']
#   let g:UltiSnipsExpandTrigger="<Down>"
# '''










